// ============================================================
// namedayInfo.js — ursprung och betydelse för almanackans namn
//
// Täcker samtliga namn i namedays.js. `uncertain: true` sätts där
// namnforskningen inte är enig — modalen skriver då ut att härledningen
// är omtvistad hellre än att låtsas säkerhet.
// ============================================================

export const NAME_INFO = {
  // Åtta av almanackans dagar bär en helg i namnets ställe. De har ingen
  // etymologi, så de får en `note` som modalen renderar i stället för
  // Ursprung/Betydelse.
  "Nyårsdagen": { note: "Årets första dag. I den svenska almanackan har den aldrig burit något personnamn — helgen har platsen." },
  "Kyndelsmässodagen": { note: "Kyndelsmässan, 40 dagar efter jul. Namnet kommer av fornsvenskans kyndel, 'ljus' — kyrkans ljus välsignades denna dag." },
  "Skottdagen": { note: "Den dag som bara finns vart fjärde år, när kalendern hinner ikapp jordens varv kring solen." },
  "Marie bebådelsedag": { note: "Vårfrudagen, nio månader före jul. I folkmun blev Vårfrudagen 'Våffeldagen' — och våfflorna blev kvar." },
  "Johannes Döparens dag": { note: "Midsommardagen i kyrkans kalender, till minne av Johannes Döparen — sommarens motsvarighet till julen." },
  "Allhelgonadagen": { note: "Allhelgonadagen, till minne av alla helgon. Alla helgons dag firas numera lördagen närmast efter." },
  "Julafton": { note: "Julafton. I Sverige — till skillnad från det mesta av världen — är det aftonen och inte juldagen som är julens mittpunkt." },
  "Juldagen": { note: "Juldagen, Kristi födelses dag. Före reformationen inleddes den med julottan i mörkret." },

  "Abel": { origin: "hebreiska Hevel", meaning: "'andedräkt' eller 'förgänglighet'" },
  "Abraham": { origin: "hebreiska Avraham", meaning: "'fader till många folk'" },
  "Ada": { origin: "kortform av Adelheid", meaning: "'av ädel börd'" },
  "Adam": { origin: "hebreiska", meaning: "'jord' eller 'människa'", famous: ["Adam, den första människan enligt Bibeln", "Adam Tensta, rappare"] },
  "Adela": { origin: "fornhögtyska Adala", meaning: "'den ädla', till adal 'ädel börd, ätt'" },
  "Adolf": { origin: "fornhögtyska Athalwolf", meaning: "'ädel varg' — adal 'ädel' + wolf 'varg'" },
  "Adrian": { origin: "latin Hadrianus", meaning: "'mannen från Hadria', en stad i norra Italien" },
  "Adriana": { origin: "femininform av Adrian", meaning: "'kvinnan från Hadria'" },
  "Agata": { origin: "grekiska Agathe", meaning: "'den goda'" },
  "Agda": { origin: "svensk kortform av Agata", meaning: "'den goda'" },
  "Agne": { origin: "fornnordiska Agni", meaning: "osäker betydelse; har förts till agi 'fruktan, respekt'", uncertain: true },
  "Agnes": { origin: "grekiska Hagne", meaning: "'ren, kysk'; tidigt sammanblandat med latin agnus 'lamm'" },
  "Agneta": { origin: "nordisk form av Agnes", meaning: "'ren, kysk'" },
  "Aina": { origin: "nordiskt namn, möjligen till fornnordiska einn 'en'", meaning: "'den enda'; kan även vara kortform av namn på Ain-", uncertain: true },
  "Aino": { origin: "finska Aino", meaning: "'den enda'; kvinnogestalt i Kalevala" },
  "Albert": { origin: "fornhögtyska Adalbert", meaning: "'ädel och lysande' — adal 'ädel' + beraht 'strålande'" },
  "Albertina": { origin: "latiniserad femininform av Albert", meaning: "'ädel och lysande'" },
  "Albin": { origin: "latin Albinus", meaning: "'den vita'", famous: ["Albin Lee Meldau, musiker"] },
  "Alexander": { origin: "grekiska Alexandros", meaning: "'den som skyddar män' — alexein 'värja' + aner 'man'" },
  "Alexandra": { origin: "femininform av Alexander", meaning: "'den som skyddar män'" },
  "Alexis": { origin: "grekiska Alexios", meaning: "'försvarare', till alexein 'värja, skydda'" },
  "Alf": { origin: "fornnordiska Alfr", meaning: "'alv', ett naturväsen i nordisk mytologi" },
  "Alfhild": { origin: "fornnordiska Alfhildr", meaning: "'alvstrid' — alfr 'alv' + hildr 'strid'" },
  "Alfons": { origin: "germanska Adalfuns, via spanska Alfonso", meaning: "'ädel och stridsberedd'; förleden omdiskuterad", uncertain: true },
  "Alfred": { origin: "fornengelska Ælfræd", meaning: "'den som får råd av alverna' — ælf 'alv' + ræd 'råd'" },
  "Alfrida": { origin: "femininform av Alfred, alternativt fornnordiska Alfríðr", meaning: "'alvråd' respektive 'vacker som en alv'", uncertain: true },
  "Algot": { origin: "fornnordiska Algautr", meaning: "'helt igenom göt' — al 'all, helt' + Gautr 'göt'" },
  "Alice": { origin: "fransk kortform av Adelheid, via Adelais", meaning: "'av ädel börd'" },
  "Allan": { origin: "keltiska Alan, av bretonskt ursprung", meaning: "osäker betydelse; tolkats som 'klippa' eller 'hjort'", uncertain: true },
  "Alma": { origin: "latin almus", meaning: "'närande, mild, välgörande'" },
  "Alrik": { origin: "fornnordiska Alríkr", meaning: "'den helt igenom mäktige' — al 'all' + ríkr 'mäktig'" },
  "Alva": { origin: "femininform av Alf", meaning: "'alv', kvinnligt naturväsen" },
  "Alvar": { origin: "fornnordiska Alfarr", meaning: "'alvkrigaren' — alfr 'alv' + herr 'krigare'" },
  "Amalia": { origin: "germanska amal", meaning: "'strävsam, tapper'; knutet till den gotiska ätten amalerna" },
  "Amanda": { origin: "latin amanda", meaning: "'den som bör älskas', till amare 'älska'" },
  "Amelie": { origin: "fransk form av Amalia", meaning: "'strävsam, tapper'" },
  "Anders": { origin: "grekiska Andreas", meaning: "'manlig, modig'", famous: ["Anders Zorn (1860–1920), målare", "Anders Tegnell, epidemiolog"] },
  "André": { origin: "fransk form av Andreas", meaning: "'manlig, modig'" },
  "Andrea": { origin: "femininform av Andreas", meaning: "'manlig, modig'" },
  "Andreas": { origin: "grekiska Andreas", meaning: "'manlig, modig', till andreios 'manlig'" },
  "Angela": { origin: "latin angela, till grekiska angelos", meaning: "'budbärare, ängel'" },
  "Angelika": { origin: "latin angelica", meaning: "'änglalik, änglalik kvinna'" },
  "Anita": { origin: "spansk kortform av Ana (Anna)", meaning: "'nåd, barmhärtighet'" },
  "Anna": { origin: "hebreiska Hannah", meaning: "'nåd' eller 'välsignad'", famous: ["Anna Lindh (1957–2003), utrikesminister"] },
  "Anneli": { origin: "sammansättning av Anna och Li (Elisabet)", meaning: "'nåd' + 'min Gud är fullkomlig'" },
  "Annette": { origin: "fransk diminutiv av Anna", meaning: "'lilla Anna', till hebreiska Hannah 'nåd'" },
  "Annika": { origin: "nordisk diminutiv av Anna, via lågtyska Anneke", meaning: "'nåd, barmhärtighet'" },
  "Anselm": { origin: "fornhögtyska Anshelm", meaning: "'gudomligt skydd' — ans 'gud, as' + helm 'hjälm'" },
  "Ansgar": { origin: "fornhögtyska Ansgar", meaning: "'gudaspjut' — ans 'gud, as' + ger 'spjut'" },
  "Anton": { origin: "latin Antonius, romerskt släktnamn", meaning: "betydelsen okänd; namnet är troligen av etruskiskt ursprung", uncertain: true },
  "Antonia": { origin: "femininform av latin Antonius", meaning: "betydelsen okänd; släktnamnet är troligen etruskiskt", uncertain: true },
  "Arne": { origin: "fornnordiska Arni", meaning: "'örn', till ǫrn" },
  "Arnold": { origin: "fornhögtyska Arnwald", meaning: "'den som härskar som en örn' — arn 'örn' + wald 'härska'" },
  "Aron": { origin: "hebreiska Aharon", meaning: "osäker betydelse; tolkats som 'den upphöjde', möjligen egyptiskt ursprung", uncertain: true },
  "Artur": { origin: "keltiska Arthur", meaning: "osäker betydelse; förts till kymriska arth 'björn' eller latin Artorius", uncertain: true },
  "Arvid": { origin: "fornnordiska Arnviðr", meaning: "'örnkämpe' — ǫrn 'örn' + viðr 'träd, kämpe'" },
  "Assar": { origin: "fornnordiska Ǫzurr, av äldre Ansuarr", meaning: "'gudavärn' — ans 'gud, as' + varr 'värn, skydd'" },
  "Asta": { origin: "kortform av Astrid", meaning: "'gudomlig skönhet' — áss 'gud, as' + fríðr 'vacker'" },
  "Astrid": { origin: "fornnordiska Ástríðr", meaning: "'gudomligt vacker'", famous: ["Astrid Lindgren (1907–2002), författare", "Drottning Astrid av Belgien"] },
  "August": { origin: "latin Augustus", meaning: "'den upphöjde, vördnadsvärde'; romersk kejsartitel" },
  "Augusta": { origin: "femininform av August", meaning: "'den upphöjda, vördnadsvärda'" },
  "Aurora": { origin: "latin aurora", meaning: "'morgonrodnad'; namn på den romerska gryningsgudinnan" },
  "Axel": { origin: "nordisk form av hebreiska Absalom", meaning: "'fadern är frid' — av 'fader' + shalom 'frid'" },
  "Axelina": { origin: "latiniserad femininform av Axel", meaning: "'fadern är frid'" },
  "Baltsar": { origin: "akkadiska Belsharusur, via Belsassar", meaning: "'Bel skydde konungen'; en av de tre vise männen" },
  "Barbara": { origin: "grekiska barbaros", meaning: "'den främmande, den utländska'" },
  "Barbro": { origin: "nordisk form av Barbara", meaning: "'den främmande, den utländska'" },
  "Bartolomeus": { origin: "arameiska bar Talmai", meaning: "'Talmajs son'" },
  "Beata": { origin: "latin beatus", meaning: "'välsignad, salig'" },
  "Beatrice": { origin: "italiensk form av latin Beatrix", meaning: "'den som gör lycklig, lyckobringerska'" },
  "Beda": { origin: "fornengelska", meaning: "'den bedjande' — efter den helige Beda venerabilis", famous: ["Beda venerabilis (672–735), engelsk munk och historiker"] },
  "Bengt": { origin: "latin Benedictus", meaning: "'välsignad'", famous: ["Bengt Ekerot, skådespelare", "Bengt Feldreich, programledare"] },
  "Benjamin": { origin: "hebreiska Binjamin", meaning: "'högra handens son', dvs. lyckans son — ben 'son' + jamin 'höger'" },
  "Berit": { origin: "nordisk kortform av Birgitta", meaning: "'den upphöjda, den starka', till keltiska Brigid" },
  "Bernhard": { origin: "fornhögtyska Bernhard", meaning: "'stark som en björn' — bern 'björn' + hard 'hård, stark'" },
  "Bernt": { origin: "nordisk kortform av Bernhard", meaning: "'stark som en björn'" },
  "Bert": { origin: "kortform av namn på -bert, t.ex. Albert", meaning: "'lysande, glänsande', till fornhögtyska beraht" },
  "Berta": { origin: "fornhögtyska Berahta", meaning: "'den strålande'" },
  "Berthold": { origin: "fornhögtyska Berahtwald", meaning: "'den strålande härskaren', av beraht 'strålande' + waltan 'härska'" },
  "Bertil": { origin: "svensk form av Berthold", meaning: "'den strålande härskaren'" },
  "Birger": { origin: "fornnordiska Birgir", meaning: "'den som hjälper', till bjarga 'bärga, rädda'" },
  "Birgit": { origin: "kortform av Birgitta, av iriska Brighid", meaning: "'den upphöjda' eller 'den starka'" },
  "Birgitta": { origin: "iriska Brigit", meaning: "'den upphöjda'", famous: ["Heliga Birgitta (1303–1373)", "Birgitta Dahl, talman"] },
  "Bjarne": { origin: "fornnordiska Bjarni", meaning: "'björn'" },
  "Björn": { origin: "fornnordiska Bjǫrn", meaning: "'björn'" },
  "Blenda": { origin: "svenskt sägennamn", meaning: "kvinnan som enligt sägnen ledde Värends kvinnor mot danskarna", famous: ["Blenda — hjältinna i smålandssägnen"] },
  "Bo": { origin: "fornnordiska Búi", meaning: "'den bofaste', till búa 'bo'" },
  "Bodil": { origin: "fornnordiska Bóthildr", meaning: "'bot' + 'strid', av bót 'bot, bättring' + hildr 'strid'" },
  "Boel": { origin: "kortform av Bodil (fornnordiska Bóthildr)", meaning: "'bot, bättring' + 'strid'" },
  "Borghild": { origin: "fornnordiska Borghildr", meaning: "'skydd' + 'strid', av borg 'borg, skydd' + hildr 'strid'" },
  "Boris": { origin: "ryska Boris, kanske kortform av Borislav", meaning: "'kämpe' — ursprunget är omdiskuterat", uncertain: true },
  "Botvid": { origin: "fornnordiska Bótviðr", meaning: "'bot, bättring' + viðr 'träd' eller 'kämpe'", uncertain: true },
  "Britta": { origin: "kortform av Birgitta", meaning: "'den upphöjda'" },
  "Bror": { origin: "fornnordiska Bróðir", meaning: "'bror'" },
  "Bruno": { origin: "fornhögtyska Bruno", meaning: "'den brune'" },
  "Brynolf": { origin: "fornnordiska Brynjulfr", meaning: "'brynjevargen', av brynja 'brynja' + ulfr 'varg'" },
  "Börje": { origin: "svensk form av Birger", meaning: "'den som hjälper'" },
  "Camilla": { origin: "latin Camilla, femininform av Camillus", meaning: "'ung tempeltjänare vid offerriter'" },
  "Carina": { origin: "kortform av Katarina, ibland till latin cara 'kär'", meaning: "'den rena' eller 'den kära'", uncertain: true },
  "Carita": { origin: "latin caritas", meaning: "'kärlek, barmhärtighet'" },
  "Carola": { origin: "femininform av latin Carolus (Karl)", meaning: "'fri man'" },
  "Cecilia": { origin: "latin Caecilia, femininform av släktnamnet Caecilius", meaning: "'den blinda', till caecus 'blind'" },
  "Charlotta": { origin: "fransk femininform av Karl", meaning: "'fri kvinna'" },
  "Christel": { origin: "tysk kortform av Christina", meaning: "'den kristna', till grekiska christos 'den smorde'" },
  "Conny": { origin: "kortform av Konrad", meaning: "'den djärve rådgivaren', av kuoni 'djärv' + rat 'råd'" },
  "Dag": { origin: "fornnordiska Dagr", meaning: "'dag'" },
  "Daga": { origin: "femininform av Dag", meaning: "'dag'" },
  "Dagmar": { origin: "fornnordiska Dagmær", meaning: "'dagens mö', av dagr 'dag' + mær 'mö'" },
  "Dagny": { origin: "fornnordiska Dagný", meaning: "'ny dag', av dagr 'dag' + ný 'ny'" },
  "Daniel": { origin: "hebreiska", meaning: "'Gud är min domare'", famous: ["Prins Daniel av Sverige", "Daniel Norgren, musiker"] },
  "Daniela": { origin: "femininform av hebreiska Daniel", meaning: "'Gud är min domare'" },
  "David": { origin: "hebreiska Dawid", meaning: "'den älskade'" },
  "Denise": { origin: "fransk femininform av Denis, av grekiska Dionysios", meaning: "'tillägnad guden Dionysos'" },
  "Dennis": { origin: "engelsk form av Denis, av grekiska Dionysios", meaning: "'tillägnad guden Dionysos'" },
  "Desideria": { origin: "latin Desideria, femininform av Desiderius", meaning: "'den efterlängtade', till desiderium 'längtan'" },
  "Desirée": { origin: "franska Désirée, av latin desiderata", meaning: "'den efterlängtade'" },
  "Diana": { origin: "latin Diana, romersk jakt- och månegudinna", meaning: "'den gudomliga' eller 'den lysande'" },
  "Dick": { origin: "engelsk kortform av Richard", meaning: "'den starke härskaren', av rik 'mäktig' + hard 'hård, stark'" },
  "Disa": { origin: "fornnordiska Dísa, till dís", meaning: "'gudinna' eller 'kvinnligt högre väsen'" },
  "Doris": { origin: "grekiska Doris, havsnymf i grekisk mytologi", meaning: "'kvinnan från Doris', dorernas landskap" },
  "Dorotea": { origin: "grekiska Dorothea", meaning: "'Guds gåva', av doron 'gåva' + theos 'gud'" },
  "Douglas": { origin: "skotsk gaeliska Dubhglas, ursprungligen ett ort- och släktnamn", meaning: "'den mörka strömmen', av dubh 'mörk' + glas 'blågrön'" },
  "Ebba": { origin: "femininform av Ebbe, kortform av namn på Ed-", meaning: "'rikedom, lycka', till fornengelska ead" },
  "Ebbe": { origin: "dansk kortform av Esbjörn (fornnordiska Ásbjǫrn)", meaning: "'gudarnas björn', av áss 'gud' + bjǫrn 'björn'", uncertain: true },
  "Edgar": { origin: "fornengelska Eadgar", meaning: "'lyckans spjut', av ead 'rikedom, lycka' + gar 'spjut'" },
  "Edit": { origin: "fornengelska Eadgyth", meaning: "'rikedom' + 'strid', av ead 'rikedom, lycka' + gyth 'strid'" },
  "Edla": { origin: "svensk kortform av namn på Ed-, kanske till tyska edel 'ädel'", meaning: "'den ädla' eller 'rikedom, lycka'", uncertain: true },
  "Edmund": { origin: "fornengelska Eadmund", meaning: "'den som skyddar sin rikedom', av ead 'rikedom' + mund 'skydd'" },
  "Edvard": { origin: "fornengelska Eadweard", meaning: "'den som vaktar sin egendom', av ead 'rikedom' + weard 'väktare'" },
  "Edvin": { origin: "fornengelska Eadwine", meaning: "'lyckans vän', av ead 'rikedom, lycka' + wine 'vän'" },
  "Egon": { origin: "tyska Egon, till fornhögtyska agin", meaning: "'svärdsegg'" },
  "Eilert": { origin: "lågtysk form av Egilhard", meaning: "'svärdsegg' + 'hård, stark'" },
  "Einar": { origin: "fornnordiska Einarr", meaning: "'den som kämpar ensam', av einn 'en, ensam' + herr 'krigare'" },
  "Eivor": { origin: "fornnordiska Eyvǫr", meaning: "'lycka' + 'varsam' — ledernas betydelse är omdiskuterad", uncertain: true },
  "Eleonora": { origin: "provensalska Aliénor, ursprunget är omdiskuterat", meaning: "kanske 'den barmhärtiga', till grekiska eleos 'medlidande'", uncertain: true },
  "Elias": { origin: "grekisk form av hebreiska Elijahu", meaning: "'min Gud är Herren'" },
  "Elin": { origin: "svensk form av Helena (grekiska Helene)", meaning: "'den strålande' eller 'facklan'" },
  "Elis": { origin: "svensk kortform av Elias", meaning: "'min Gud är Herren'" },
  "Elisabet": { origin: "hebreiska Elisheva", meaning: "'Gud är min ed' eller 'åt Gud helgad'" },
  "Elise": { origin: "kortform av Elisabet", meaning: "'Gud är min ed'" },
  "Ella": { origin: "kortform av Eleonora, Elisabet eller Helena", meaning: "'Gud är min ed' — betydelsen följer det namn Ella förkortar" },
  "Ellen": { origin: "engelsk form av Helena, besläktat med Elin", meaning: "'den strålande' eller 'facklan'" },
  "Ellinor": { origin: "variant av Eleonora", meaning: "kanske 'den barmhärtiga' — ursprunget är omdiskuterat", uncertain: true },
  "Elof": { origin: "fornnordiska Eileifr", meaning: "'den evige arvingen', av ei 'alltid' + leifr 'arvinge'" },
  "Elsa": { origin: "kortform av Elisabet", meaning: "'Gud är min ed'" },
  "Elvira": { origin: "spanska Elvira, av ett västgotiskt namn", meaning: "kanske 'den beskyddande' — ledernas betydelse är osäker", uncertain: true },
  "Emanuel": { origin: "hebreiska Immanuel", meaning: "'Gud med oss'" },
  "Emil": { origin: "latin Aemilius, romerskt släktnamn", meaning: "'den ivrige', till aemulus 'tävlande, ivrig'" },
  "Emilia": { origin: "femininform av latin Aemilius", meaning: "'den ivriga', till aemulus 'tävlande, ivrig'" },
  "Emma": { origin: "fornhögtyska", meaning: "'helande, allomfattande'", famous: ["Emma Frans, vetenskapsjournalist"] },
  "Enar": { origin: "svensk variant av Einar", meaning: "'den som kämpar ensam'" },
  "Engelbrekt": { origin: "fornhögtyska Engilberht", meaning: "'den strålande angeln', av folknamnet angler + beraht 'strålande'" },
  "Erhard": { origin: "fornhögtyska Erhard", meaning: "'ära' och 'hård, stark' — den ärofullt starke" },
  "Erik": { origin: "fornnordiska Eiríkr", meaning: "'evig härskare'", famous: ["Erik den helige, Sveriges skyddshelgon"] },
  "Erika": { origin: "femininform av Erik (fornnordiska Eiríkr)", meaning: "'allena härskande' eller 'evig härskare'" },
  "Erland": { origin: "fornnordiska Erlendr", meaning: "'främling' eller 'den som är i utlandet'" },
  "Erling": { origin: "fornnordiska Erlingr, avlett av jarl", meaning: "'jarlens son' eller 'ättling till jarlen'" },
  "Erna": { origin: "femininform av Ernst", meaning: "'allvarlig, beslutsam'", uncertain: true },
  "Ernst": { origin: "fornhögtyska ernust 'allvar, kamp'", meaning: "'den allvarlige' eller 'den beslutsamme'" },
  "Esaias": { origin: "hebreiska Yesha'yahu (Jesaja)", meaning: "'Herren är frälsning'" },
  "Esbjörn": { origin: "fornnordiska Ásbjǫrn", meaning: "'gudabjörn', av 'asagud' och 'björn'" },
  "Eskil": { origin: "fornnordiska Áskell, av Ásketill", meaning: "'gudarnas offerkittel', av 'gud' och 'kittel'" },
  "Estelle": { origin: "franska Estelle, av latin stella", meaning: "'stjärna'" },
  "Ester": { origin: "persiska/hebreiska", meaning: "'stjärna'", famous: ["Drottning Ester i Bibeln"] },
  "Eugen": { origin: "grekiska Eugenios", meaning: "'välboren' eller 'av god börd'" },
  "Eugenia": { origin: "femininform av Eugen (grekiska Eugenia)", meaning: "'den välborna'" },
  "Eva": { origin: "hebreiska Chawwah", meaning: "'liv' eller 'levande'", famous: ["Eva Dahlgren, sångerska", "Eva Rusz, psykolog"] },
  "Evald": { origin: "fornhögtyska Ewald", meaning: "'lag' och 'härska' — den som råder över lagen" },
  "Evelina": { origin: "franska Aveline, diminutiv av germanska Avila", meaning: "betydelsen är omdiskuterad; namnet har i Norden ofta anslutits till Eva 'liv'", uncertain: true },
  "Evert": { origin: "lågtyska form av Everhard (Eberhard)", meaning: "'vildsvin' och 'hård, stark' — stark som ett vildsvin" },
  "Evy": { origin: "svensk smekform av Eva (hebreiska Chawwah)", meaning: "'liv' eller 'den levande'" },
  "Fabian": { origin: "latin Fabianus, till släktnamnet Fabius", meaning: "'den som hör till ätten Fabius'; Fabius har härletts ur faba 'böna'" },
  "Fanny": { origin: "engelsk kortform av Frances (Franciska)", meaning: "'den frankiska' eller 'fransyskan'" },
  "Fatima": { origin: "arabiska Fāṭima, till roten f-ṭ-m 'avvänja'", meaning: "'den som avvänjer sitt barn'" },
  "Felicia": { origin: "femininform av latin Felix", meaning: "'den lyckliga'" },
  "Felix": { origin: "latin felix", meaning: "'lycklig' eller 'framgångsrik'" },
  "Ferdinand": { origin: "västgotiskt namn, via spanska Fernando", meaning: "'den djärve'; efterledens 'modig, vågsam' är säker, förledens tolkning omdiskuterad", uncertain: true },
  "Filip": { origin: "grekiska Philippos", meaning: "'hästälskare'", famous: ["Filip Hammar, programledare"] },
  "Filippa": { origin: "femininform av Filip (grekiska Philippos)", meaning: "'hästvän', av 'vän' och 'häst'" },
  "Fingal": { origin: "gaeliska Fionnghall", meaning: "'den ljuse främlingen' — i keltisk tradition en beteckning på nordbor" },
  "Finn": { origin: "fornnordiska Finnr", meaning: "'finne' eller 'same' — ursprungligen en folkbeteckning" },
  "Folke": { origin: "fornnordiska Folki", meaning: "'den som leder folket' eller 'härförare'" },
  "Franciska": { origin: "femininform av Franciskus (latin Franciscus)", meaning: "'den frankiska' eller 'fransyskan'" },
  "Frank": { origin: "germanska folknamnet frank", meaning: "'frank' eller 'fri man'" },
  "Frans": { origin: "svensk form av latin Franciscus", meaning: "'frank' eller 'fransman'" },
  "Fredrik": { origin: "fornhögtyska Fridurih", meaning: "'fredlig härskare', av 'fred, skydd' och 'härskare'" },
  "Fredrika": { origin: "femininform av Fredrik", meaning: "'fredlig härskarinna'" },
  "Frej": { origin: "fornnordiska Freyr, namn på fruktbarhetsguden", meaning: "'herren' eller 'härskaren'" },
  "Freja": { origin: "fornnordiska Freyja, namn på kärleks- och fruktbarhetsgudinnan", meaning: "'härskarinnan' eller 'frun'" },
  "Frida": { origin: "fornnordiska Fríðr", meaning: "'vacker' eller 'fred'", famous: ["Frida Lyngstad i ABBA"] },
  "Frideborg": { origin: "nordisk bildning, fornnordiska Fríðborg", meaning: "'fred, skydd' och 'värn' — den fridsamma beskyddarinnan" },
  "Fridolf": { origin: "fornhögtyska Fridulf", meaning: "'fred' och 'varg'" },
  "Fritiof": { origin: "fornnordiska Friðþjófr", meaning: "'fredstjuven', den som rövar bort friden" },
  "Fritz": { origin: "tysk kortform av Friedrich (Fredrik)", meaning: "'fredlig härskare'" },
  "Gabriel": { origin: "hebreiska", meaning: "'Guds kraft'", famous: ["Ärkeängeln Gabriel", "Gabriel Forss, dirigent"] },
  "Gabriella": { origin: "femininform av Gabriel (hebreiska Gavri'el)", meaning: "'Gud är min styrka'" },
  "Georg": { origin: "grekiska Georgios", meaning: "'jordbrukare' eller 'bonde', av 'jord' och 'arbete'" },
  "Gerd": { origin: "fornnordiska Gerðr, namn på jättedottern som Frej friade till", meaning: "'den inhägnade' eller 'den skyddade', till garðr 'gård, hägnad'" },
  "Gerda": { origin: "nordisk sidoform av fornnordiska Gerðr", meaning: "'den inhägnade' eller 'den skyddade'" },
  "Gerhard": { origin: "fornhögtyska Gerhard", meaning: "'spjut' och 'hård, stark' — stark med spjutet" },
  "Germund": { origin: "fornnordiska Geirmundr", meaning: "'spjut' och 'skydd' — den som skyddar med spjutet" },
  "Gert": { origin: "lågtysk kortform av Gerhard", meaning: "'spjut' och 'hård, stark'" },
  "Gertrud": { origin: "fornhögtyska Gerdrud", meaning: "'spjut' och 'styrka' — den spjutstarka" },
  "Gilbert": { origin: "fornhögtyska Gisilbert", meaning: "'ättling' och 'lysande, ryktbar' — den lysande ättlingen" },
  "Gisela": { origin: "fornhögtyska Gisila, till gisal", meaning: "'gisslan' — ursprungligen om furstebarn som lämnades som säkerhet" },
  "Glenn": { origin: "gaeliska gleann, ursprungligen ort- och släktnamn", meaning: "'dal' eller 'dalgång'" },
  "Gottfrid": { origin: "fornhögtyska Godafrid", meaning: "'gud' och 'fred' — Guds beskydd" },
  "Gotthard": { origin: "fornhögtyska Godahard", meaning: "'gud' och 'hård, stark' — stark genom Gud" },
  "Greger": { origin: "svensk form av latin Gregorius, av grekiska gregorein 'vaka'", meaning: "'den vaksamme'" },
  "Greta": { origin: "fornsvenska, kortform av Margareta", meaning: "'pärla'", famous: ["Greta Garbo (1905–1990), skådespelerska", "Greta Thunberg, klimataktivist"] },
  "Gudmar": { origin: "fornnordiska Guðmarr", meaning: "'gud' och 'ryktbar' — den gudaberömde" },
  "Gudmund": { origin: "fornnordiska Guðmundr", meaning: "'gud' och 'skydd' — den som gudarna skyddar" },
  "Gudrun": { origin: "fornnordiska Guðrún", meaning: "'gud' och 'runa, hemlighet' — den som känner gudarnas hemligheter" },
  "Gun": { origin: "fornnordiska Gunnr, valkyrienamn; även kortform av Gunhild och Gunborg", meaning: "'strid' eller 'kamp'" },
  "Gunborg": { origin: "fornnordiska Gunnbjǫrg", meaning: "'strid' och 'hjälp, skydd' — den som skyddar i striden" },
  "Gunder": { origin: "dansk-nordisk form av Gunnar (fornnordiska Gunnarr)", meaning: "'strid' och 'krigare, här'" },
  "Gunhild": { origin: "fornnordiska Gunnhildr", meaning: "'strid' och 'kamp' — båda lederna betyder strid" },
  "Gunilla": { origin: "svensk form av Gunhild", meaning: "'strid' och 'kamp'" },
  "Gunnar": { origin: "fornnordiska Gunnarr", meaning: "'krigskämpe'", famous: ["Gunnar Sträng (1906–1992), finansminister"] },
  "Gunnel": { origin: "svensk kortform av Gunhild", meaning: "'strid' och 'kamp'" },
  "Gunvor": { origin: "fornnordiska Gunnvǫr", meaning: "'strid' och 'varsam, aktsam' — den vaksamma i striden" },
  "Gustav": { origin: "fornsvenska Gøtstaf", meaning: "'götarnas stav', dvs. götarnas stöd; en slavisk härledning ur Gostislav har också föreslagits", uncertain: true },
  "Gustav Adolf": { origin: "dubbelnamn: fornsvenska Gøtstaf och fornhögtyska Adalwolf", meaning: "'götarnas stöd' och 'ädel varg'; förleden i Gustav är omdiskuterad", uncertain: true },
  "Göran": { origin: "svensk form av Georgius (Georg), via lågtyska Jörgen", meaning: "'jordbrukare' eller 'bonde'" },
  "Görel": { origin: "svensk form av fornnordiska Gyríðr, alternativt folklig form av Gertrud", meaning: "'spjut' och 'vacker, älskad'", uncertain: true },
  "Gösta": { origin: "svensk folkform av Gustav", meaning: "'götarnas stöd' (se Gustav)" },
  "Göta": { origin: "femininform av Göte, till folknamnet göt", meaning: "'kvinna av götarnas stam'" },
  "Göte": { origin: "fornsvenska Gøte, till folknamnet göt", meaning: "'göt', man av götarnas stam" },
  "Hakon": { origin: "fornnordiska Hákon", meaning: "'hög, förnäm' och 'ättling, son' — den högättade sonen" },
  "Halvar": { origin: "fornnordiska Hallvarðr", meaning: "'sten, klippa' och 'väktare' — klippans väktare" },
  "Halvard": { origin: "fornnordiska Hallvarðr", meaning: "'klippans väktare'", famous: ["Sankt Hallvard, Oslos skyddshelgon"] },
  "Hampus": { origin: "lågtysk kortform av Hans (Johannes)", meaning: "'Herren är nådig'", uncertain: true },
  "Hanna": { origin: "hebreiska Hannah", meaning: "'nåd' eller 'den benådade'" },
  "Hannele": { origin: "finsk diminutivform av Hanna", meaning: "'lilla Hanna', till hebreiskans 'nåd'" },
  "Hans": { origin: "kortform av Johannes", meaning: "'Gud är nådig'", famous: ["Hans Alfredson (1931–2017), komiker", "Hans Rosling (1948–2017), professor"] },
  "Harald": { origin: "fornnordiska Haraldr", meaning: "'härskaren över hären', av harja 'krigsskara' och valdr 'härskare'" },
  "Harriet": { origin: "engelsk femininform av Henrik, via franska Henriette", meaning: "'hemmets härskarinna'" },
  "Harry": { origin: "engelsk form av Henrik", meaning: "'hemmets härskare', av heim 'hem' och rik 'mäktig'" },
  "Hedvig": { origin: "fornhögtyska Hadewig", meaning: "'strid, kamp', av hadu 'strid' och wig 'kamp'" },
  "Heidi": { origin: "tysk kortform av Adelheid", meaning: "'den av ädel börd'" },
  "Helena": { origin: "grekiska Heléne", meaning: "'fackla' eller 'glans'", famous: ["Heliga Helena, Konstantins mor", "Helena Bergström, skådespelerska"] },
  "Helga": { origin: "fornnordiska Helga, femininform av Helge", meaning: "'helig, invigd'" },
  "Helge": { origin: "fornnordiska Helgi", meaning: "'helig, invigd åt gudarna'" },
  "Helmer": { origin: "yngre nordisk form av Hjalmar", meaning: "'hjälmkrigaren', av hjalmr 'hjälm' och arr 'krigare'" },
  "Helny": { origin: "nordisk nybildning, troligen till Hel- i Helga", meaning: "osäker betydelse; efterleden -ny kan höra till nordiskt ný 'ny'", uncertain: true },
  "Hemming": { origin: "fornnordiska Hemingr", meaning: "'den som byter hamn', till hamr 'skepnad, djurhamn'" },
  "Henning": { origin: "lågtysk kortform av Henrik", meaning: "'hemmets härskare'" },
  "Henrietta": { origin: "femininform av Henrik, via franska Henriette", meaning: "'hemmets härskarinna'" },
  "Henrik": { origin: "fornhögtyska Haimirich", meaning: "'härskare över hemmet'", famous: ["Henrik Schyffert, komiker"] },
  "Henrika": { origin: "femininform av Henrik", meaning: "'hemmets härskarinna', av heim 'hem' och rik 'mäktig'" },
  "Herbert": { origin: "fornhögtyska Heribert", meaning: "'den som lyser i hären', av heri 'krigsskara' och beraht 'lysande'" },
  "Herman": { origin: "fornhögtyska Hariman", meaning: "'krigsmannen', av hari 'här, krigsskara' och man 'man'" },
  "Hermine": { origin: "tysk femininform av Herman", meaning: "'krigskvinnan', till hari 'här, krigsskara'" },
  "Hervor": { origin: "fornnordiska Hervǫr", meaning: "'den som vakar över hären', av herr 'krigsskara' och vǫr 'varsam, aktsam'" },
  "Hilda": { origin: "fornnordiska Hildr, kortform av namn på Hild-", meaning: "'strid, kamp'" },
  "Hilde": { origin: "tysk och nordisk form av Hilda", meaning: "'strid, kamp'" },
  "Hildegard": { origin: "fornhögtyska Hildegard", meaning: "'stridens skydd', av hild 'strid' och gard 'skydd, inhägnad'" },
  "Hilding": { origin: "fornnordiska Hildingr", meaning: "'krigaren, hövdingen', till hildr 'strid'" },
  "Hillevi": { origin: "nordisk form av fornhögtyska Heilwig", meaning: "'den lyckosamma i strid', av heil 'hel, lycka' och wig 'kamp'" },
  "Hjalmar": { origin: "fornnordiska Hjálmarr", meaning: "'hjälmkrigaren', av hjalmr 'hjälm' och arr 'krigare'" },
  "Hjördis": { origin: "fornnordiska Hjǫrdís", meaning: "'svärdsgudinnan', av hjǫrr 'svärd' och dís 'gudinna, kvinna'" },
  "Holger": { origin: "fornnordiska Hólmgeirr", meaning: "'holmens spjutkämpe', av holmr 'holme, ö' och geirr 'spjut'" },
  "Holmfrid": { origin: "fornnordiska Holmfríðr", meaning: "'den sköna på holmen', av holmr 'holme' och fríðr 'vacker, älskad'" },
  "Hubert": { origin: "fornhögtyska Hugubert", meaning: "'den med lysande sinne', av hugu 'sinne, tanke' och beraht 'lysande'" },
  "Hugo": { origin: "fornhögtyska Hugo", meaning: "'sinne, tanke, ande'" },
  "Hulda": { origin: "fornnordiska Hulda", meaning: "'den huldrika, milda och nådiga'" },
  "Håkan": { origin: "fornnordiska Hákon", meaning: "'den högättade sonen', av há 'hög' och konr 'son, ättling'" },
  "Ida": { origin: "fornhögtyska Ida, kortform av namn på Id-", meaning: "'den verksamma', till germanska id 'verksamhet, id'" },
  "Inez": { origin: "spansk form av Agnes", meaning: "'den rena, kyska', av grekiskans hagnos" },
  "Inga": { origin: "fornnordiska Inga, kortform av namn på Ing-", meaning: "'tillhörig guden Ing (Yngve)'" },
  "Ingalill": { origin: "svensk sammansättning av Inga och lill", meaning: "'lilla Inga'" },
  "Inge": { origin: "fornnordiska Ingi, kortform av namn på Ing-", meaning: "'tillhörig guden Ing (Yngve)'" },
  "Ingeborg": { origin: "fornnordiska", meaning: "'beskyddad av guden Ing'", famous: ["Ingeborg av Danmark, fransk drottning"] },
  "Ingegerd": { origin: "fornnordiska Ingigerðr", meaning: "'Ings skydd', av gudanamnet Ing och gerðr 'skydd, gärde'" },
  "Ingela": { origin: "svensk sidoform av Ingegärd, även diminutiv till Inga", meaning: "'den lilla Inga', till gudanamnet Ing" },
  "Ingemar": { origin: "fornnordiska Ingimárr", meaning: "'berömd genom Ing', av gudanamnet Ing och mærr 'berömd'" },
  "Ingemund": { origin: "fornnordiska Ingimundr", meaning: "'den som Ing skyddar', av gudanamnet Ing och mundr 'skydd, hand'" },
  "Inger": { origin: "dansk-norsk kortform av Ingegerd", meaning: "'Ings skydd', av gudanamnet Ing och gerðr 'skydd, gärde'" },
  "Ingrid": { origin: "fornnordiska Ingiríðr", meaning: "'vacker' av guden Ing", famous: ["Ingrid Bergman (1915–1982), skådespelerska", "Drottning Ingrid av Danmark"] },
  "Ingvar": { origin: "fornnordiska Ingvarr (Yngvarr)", meaning: "'Ings krigare', av gudanamnet Ing (Yngve) och arr 'krigare'" },
  "Ingvor": { origin: "fornnordiska Ingvǫr, femininbildning till Ing-", meaning: "'den som Ing vakar över', av gudanamnet Ing och vǫr 'varsam, aktsam'" },
  "Irene": { origin: "grekiska Eirene", meaning: "'fred'" },
  "Iris": { origin: "grekiska Iris", meaning: "'regnbåge'; regnbågens gudinna och gudarnas budbärarinna" },
  "Irja": { origin: "finsk form av Irene eller Irina", meaning: "'fred', om namnet hör till grekiskans eirene", uncertain: true },
  "Irma": { origin: "fornhögtysk kortform av namn på Irm-, som Irmgard", meaning: "'den väldiga', till germanska irmin 'stor, allomfattande'" },
  "Isabella": { origin: "spansk och italiensk form av Elisabet", meaning: "'min Gud är ed' eller 'min Gud är fullkomlighet'" },
  "Isak": { origin: "hebreiska Jitschak", meaning: "'han ler' eller 'må Gud le mot honom'" },
  "Israel": { origin: "hebreiska Jisrael", meaning: "'den som kämpar med Gud'" },
  "Ivan": { origin: "slavisk form av Johannes", meaning: "'Gud är nådig'", famous: ["Ivan den förskräcklige, rysk tsar"] },
  "Ivar": { origin: "fornnordiska Ívarr", meaning: "'bågkrigaren', av ýr 'idegran, båge' och arr 'krigare'" },
  "Jack": { origin: "engelsk smekform av John (Johannes)", meaning: "'Herren är nådig'" },
  "Jakob": { origin: "hebreiska Ja'akov", meaning: "'han håller i hälen', bildligt 'efterträdaren'" },
  "Jan": { origin: "nederländsk och nordisk kortform av Johannes", meaning: "'Herren är nådig'" },
  "Jannike": { origin: "nordisk femininform av Jan (Johannes)", meaning: "'Herren är nådig'" },
  "Jarl": { origin: "fornnordiska jarl, hövdingatitel", meaning: "'hövding, förnäm man'" },
  "Jeanette": { origin: "fransk diminutiv femininform av Jean (Johannes)", meaning: "'Herren är nådig'" },
  "Jennifer": { origin: "korniska Jenifer, av walesiska Gwenhwyfar", meaning: "'den vita, ljuva', av gwen 'vit, ljus, helig'" },
  "Jenny": { origin: "engelsk smekform av Jane (Johanna)", meaning: "'Herren är nådig'" },
  "Jens": { origin: "dansk form av Johannes", meaning: "'Herren är nådig'" },
  "Jesper": { origin: "dansk form av Kaspar, ytterst persiska", meaning: "'skattmästaren'" },
  "Jessika": { origin: "engelska Jessica, bildat av Shakespeare till bibliska Jiska", meaning: "'hon skådar' eller 'Gud skådar'" },
  "Joakim": { origin: "hebreiska Jehojakim", meaning: "'Herren upprättar' eller 'Gud reser upp'" },
  "Joar": { origin: "fornnordiska Jóarr", meaning: "'hästkrigaren', av jór 'stridshäst' och arr 'krigare'" },
  "Joel": { origin: "hebreiska Joel", meaning: "'Jahve är Gud', av Jo 'Jahve' och El 'Gud'" },
  "Johan": { origin: "hebreiska Yôhanan", meaning: "'Gud är nådig'", famous: ["Johan III av Sverige (1537–1592)", "Johan Falk, fiktiv polis"] },
  "Johanna": { origin: "femininform av Johannes", meaning: "'Herren är nådig'" },
  "Johannes": { origin: "hebreiska Jochanan", meaning: "'Herren är nådig'" },
  "John": { origin: "engelsk form av Johannes", meaning: "'Gud är nådig'", famous: ["John Blund, sömnens sagofigur"] },
  "Jon": { origin: "nordisk kortform av Johannes, hebreiska Yohanan", meaning: "'Herren är nådig'" },
  "Jonas": { origin: "hebreiska Yonah", meaning: "'duva'" },
  "Jonatan": { origin: "hebreiska Yehonatan", meaning: "'Herren har givit'" },
  "Jonna": { origin: "kortform av Johanna, femininform av Johannes", meaning: "'Herren är nådig'" },
  "Josef": { origin: "hebreiska Yosef", meaning: "'må Gud föröka'" },
  "Josefina": { origin: "femininform av Josef via franska Joséphine", meaning: "'må Gud föröka'" },
  "Judit": { origin: "hebreiska Yehudit", meaning: "'kvinna från Juda', 'judinna'" },
  "Julia": { origin: "latin Julia, femininform av släktnamnet Julius", meaning: "'kvinna ur den juliska ätten'; släktnamnets egen betydelse är omtvistad" },
  "Julius": { origin: "latin Julius, romerskt släktnamn", meaning: "'ur den juliska ätten'; ätten härledde själv namnet från Iulus, Aeneas son" },
  "Justina": { origin: "femininform av latin Justinus, till justus", meaning: "'den rättvisa'" },
  "Justus": { origin: "latin Justus", meaning: "'rättvis', 'rättfärdig'" },
  "Jörgen": { origin: "nordisk form av Georg via lågtyska, grekiska Georgios", meaning: "'jordbrukare', av gē 'jord' och ergon 'arbete'" },
  "Kaj": { origin: "dansk och frisisk form, möjligen av latin Gaius", meaning: "betydelsen oviss; Gaius har tolkats som 'den glade'", uncertain: true },
  "Kajsa": { origin: "svensk kortform av Katarina, grekiska Aikaterine", meaning: "'den rena' enligt den vanliga tolkningen" },
  "Karin": { origin: "grekiska, variant av Katarina", meaning: "'den rena'", famous: ["Karin Boye (1900–1941), poet", "Karin Bergöö Larsson, konstnär"] },
  "Karl": { origin: "fornhögtyska karl", meaning: "'fri man'", famous: ["Karl XII (1682–1718)", "Carl von Linné (1707–1778), botaniker"] },
  "Karla": { origin: "femininform av Karl, fornnordiska karl", meaning: "'fri man'" },
  "Karolina": { origin: "femininform av Karl", meaning: "'fri kvinna'", famous: ["Drottning Karolina"] },
  "Kasper": { origin: "Caspar, namnet på en av de tre vise männen, ytterst persiskt", meaning: "tolkas vanligen som 'skattmästare'", uncertain: true },
  "Katarina": { origin: "grekiska Aikaterine", meaning: "urbetydelsen är oviss; tidigt knuten till katharos 'ren'" },
  "Katja": { origin: "rysk smekform av Jekaterina, grekiska Aikaterine", meaning: "'den rena' enligt den vanliga tolkningen" },
  "Kennet": { origin: "engelska Kenneth, av gaeliska Cinaed och Coinneach", meaning: "'född av eld' respektive 'den fagre'" },
  "Kent": { origin: "engelska, av landskapsnamnet Kent eller kortform av Kenneth", meaning: "landskapsnamnets betydelse är oviss, möjligen 'kant, rand'", uncertain: true },
  "Kerstin": { origin: "svensk form av Kristina", meaning: "'den kristna'" },
  "Kim": { origin: "kortform av Joakim, i engelskan av Kimberley", meaning: "Joakim av hebreiska Jehojakim 'Herren reser upp'" },
  "Kjell": { origin: "fornnordiska Ketill", meaning: "'offerkittel', även 'hjälm'; leden hade kultisk innebörd" },
  "Klara": { origin: "latin Clara, till clarus", meaning: "'klar', 'lysande', 'berömd'" },
  "Klas": { origin: "kortform av Nikolaus, grekiska Nikolaos", meaning: "'folkets segrare', av nike 'seger' och laos 'folk'" },
  "Klemens": { origin: "latin Clemens", meaning: "'mild', 'barmhärtig'" },
  "Knut": { origin: "fornnordiska Knútr", meaning: "'knut' eller 'knöl' (kroppslig styrka)", famous: ["Knut den store, dansk kung", "Tjugondag Knut, julens slut"] },
  "Konrad": { origin: "fornhögtyska Kuonrat", meaning: "'den djärve rådgivaren', av kuoni 'djärv' och rat 'råd'" },
  "Konstantin": { origin: "latin Constantinus", meaning: "'den ståndaktige'", famous: ["Kejsar Konstantin den store"] },
  "Krister": { origin: "svensk form av Kristian, latin Christianus", meaning: "'den kristne'" },
  "Kristian": { origin: "latin Christianus, till grekiska Christos", meaning: "'den kristne'; Christos betyder 'den smorde'" },
  "Kristina": { origin: "latin Christina, femininform av Christianus", meaning: "'den kristna'" },
  "Kristoffer": { origin: "grekiska Christophoros", meaning: "'den som bär Kristus'" },
  "Kurt": { origin: "tysk kortform av Konrad", meaning: "'den djärve rådgivaren'" },
  "Lage": { origin: "fornnordiska och fordanska Laghi", meaning: "troligen till lag 'gemenskap, sällskap'", uncertain: true },
  "Laila": { origin: "norsk-samisk form av Helga; sammanfaller med arabiska Layla", meaning: "'den heliga'; arabiska Layla betyder 'natt'" },
  "Lars": { origin: "latin Laurentius", meaning: "'krönt med lager'", famous: ["Lars Lerin, akvarellmålare", "Sankt Laurentius, martyr — Larsmässan 10 augusti"] },
  "Laura": { origin: "latin Laura, till laurus", meaning: "'lager'; syftar på lagerkransen" },
  "Lea": { origin: "hebreiska Le'ah", meaning: "betydelsen oviss; tolkad som 'vildko' eller 'den matta'" },
  "Leif": { origin: "fornnordiska Leifr", meaning: "'arvinge', 'ättling'" },
  "Leila": { origin: "arabiska och persiska Layla", meaning: "'natt'" },
  "Lena": { origin: "kortform av Helena och Magdalena", meaning: "Helena har tolkats som 'den strålande', men urbetydelsen är oviss" },
  "Lennart": { origin: "svensk form av Leonard, fornhögtyska Leonhard", meaning: "'stark som ett lejon', av latin leo 'lejon' och hard 'hård, stark'" },
  "Leo": { origin: "latin Leo", meaning: "'lejon'" },
  "Leonard": { origin: "fornhögtyska Leonhard", meaning: "'stark som ett lejon', av latin leo 'lejon' och hard 'hård, stark'" },
  "Leopold": { origin: "fornhögtyska Liutbald", meaning: "'djärv bland folket', av liut 'folk' och bald 'djärv'" },
  "Lilian": { origin: "engelska Lillian, till latin lilium", meaning: "'lilja'; kan även vara en utvidgning av Elisabet" },
  "Lillemor": { origin: "svensk nybildning av lilla mor", meaning: "'lilla mor', ursprungligen ett smeknamn" },
  "Lilly": { origin: "engelska Lily, till latin lilium", meaning: "'lilja'" },
  "Linda": { origin: "kortform av germanska namn på -linda, till lind", meaning: "'sköld av lindträ', även tolkat som 'mild'" },
  "Linn": { origin: "kortform av Linnea", meaning: "efter linnean", famous: ["Linn Ullmann, norsk författare"] },
  "Linnea": { origin: "uppkallat efter blomman linnea", meaning: "blomman som Carl von Linné fick ge sitt namn", famous: ["Linnean — Smålands landskapsblomma"] },
  "Linus": { origin: "grekiska Linos", meaning: "urbetydelsen är oviss; knyts till linos, en klagosång" },
  "Lisa": { origin: "kortform av Elisabeth", meaning: "'Gud är min ed'", famous: ["Lisa Nilsson, sångerska", "Lisa Ekdahl, sångerska"] },
  "Lisbet": { origin: "kortform av Elisabet, hebreiska Elisheva", meaning: "'min Gud är fullkomlighet' eller 'Gud är min ed'" },
  "Liv": { origin: "fornnordiska Hlíf", meaning: "'skydd', 'värn'; i nutiden uppfattat som ordet liv" },
  "Lorentz": { origin: "tysk form av latin Laurentius", meaning: "'mannen från Laurentum'; ofta tolkat som 'lagerkrönt'" },
  "Lotta": { origin: "svensk kortform av Charlotta, femininform av Karl", meaning: "'fri man'" },
  "Louise": { origin: "fransk femininform av Louis, fornhögtyska Hlodwig", meaning: "'ryktbar kämpe', av hlud 'ryktbar' och wig 'strid'" },
  "Love": { origin: "svensk form av franska Louis, fornhögtyska Hlodwig", meaning: "'ryktbar kämpe'" },
  "Lovisa": { origin: "svensk form av Louise, femininform av Ludvig", meaning: "'ryktbar kämpe'" },
  "Lucia": { origin: "latin lux", meaning: "'ljus'", famous: ["Heliga Lucia av Syrakusa (283–304)", "Lucia-traditionen firas 13 dec"] },
  "Ludvig": { origin: "fornhögtyska Hlodwig", meaning: "'ryktbar kämpe', av hlud 'ryktbar' och wig 'strid'" },
  "Lukas": { origin: "latin Lucas, grekiska Loukas", meaning: "'mannen från Lucanien'; ibland knutet till lux 'ljus'" },
  "Lydia": { origin: "grekiska Lydia", meaning: "'kvinnan från Lydien', ett landskap i Mindre Asien" },
  "Madeleine": { origin: "fransk form av Magdalena", meaning: "'kvinnan från Magdala'" },
  "Magdalena": { origin: "grekiska Magdalene, till ortnamnet Magdala", meaning: "'kvinnan från Magdala' vid Gennesarets sjö" },
  "Magnhild": { origin: "fornnordiska Magnhildr", meaning: "'kraft i strid', av magn 'kraft' och hildr 'strid'" },
  "Magnus": { origin: "latin", meaning: "'den store'", famous: ["Magnus Ladulås, kung", "Magnus Uggla, musiker"] },
  "Maj": { origin: "av månaden maj / kortform av Maria", meaning: "vårmånadens namn", famous: ["Maj Sjöwall, deckarförfattare"] },
  "Majken": { origin: "svensk smekform av Maria, till kortformen Maj", meaning: "Marias betydelse är omtvistad; tolkas som 'den upphöjda' eller 'den bittra'" },
  "Majvor": { origin: "svensk nybildning av Maj och namnleden -vor", meaning: "-vor av fornnordiska vǫr 'aktsam, varsam'" },
  "Malena": { origin: "svensk kortform av Magdalena", meaning: "'kvinnan från Magdala'" },
  "Malin": { origin: "svensk kortform av Magdalena", meaning: "'kvinnan från Magdala'" },
  "Malkolm": { origin: "skotska Malcolm, gaeliska Máel Coluim", meaning: "'den helige Columbas tjänare'" },
  "Malte": { origin: "lågtysk kortform, vanligen förd till Helmold", meaning: "Helmold av helm 'hjälm' och wald 'härskare'", uncertain: true },
  "Manfred": { origin: "fornhögtyska Managfrid", meaning: "'man' och 'fred', ungefär 'den som värnar freden'" },
  "Marcus": { origin: "latin", meaning: "'tillägnad krigsguden Mars'", famous: ["Marcus Aurelius, kejsare"] },
  "Margareta": { origin: "grekiska margarítês", meaning: "'pärla'", famous: ["Drottning Margareta I av Danmark, Norge & Sverige", "Margareta Krook (1925–2001)"] },
  "Margit": { origin: "nordisk form av Margareta", meaning: "'pärla', ytterst av grekiskans margarítes" },
  "Margot": { origin: "fransk smekform av Marguerite (Margareta)", meaning: "'pärla'" },
  "Maria": { origin: "hebreiska Mirjam", meaning: "'den älskade' eller 'bitterhet'", famous: ["Jungfru Maria", "Maria Callas (1923–1977), operasångerska"] },
  "Mariana": { origin: "latin Mariana, femininform av Marianus", meaning: "'som hör till Marius'; i Norden uppfattat som utvidgning av Maria" },
  "Marianne": { origin: "franska Marianne, sammansatt av Marie och Anne", meaning: "förenar Maria med Anna, 'nåd'" },
  "Marika": { origin: "ungersk och slavisk smekform av Maria", meaning: "'den upphöjda' eller 'den bittra' — Marias betydelse är omdiskuterad" },
  "Marina": { origin: "latin Marina, femininform av Marinus", meaning: "'den som hör till havet'" },
  "Marit": { origin: "nordisk form av Margareta", meaning: "'pärla'" },
  "Marita": { origin: "nordisk smekform av Maria", meaning: "'den upphöjda' eller 'den bittra' — betydelsen är omdiskuterad" },
  "Markus": { origin: "latin Marcus", meaning: "'tillägnad krigsguden Mars'" },
  "Marlene": { origin: "tyska Marlene, sammandragning av Maria och Magdalena", meaning: "Maria förenat med 'kvinnan från Magdala'" },
  "Marta": { origin: "arameiska Marta", meaning: "'härskarinna' eller 'husets fru'" },
  "Martin": { origin: "latin Martinus", meaning: "'tillägnad krigsguden Mars'" },
  "Martina": { origin: "latin Martina, femininform av Martinus", meaning: "'tillägnad krigsguden Mars'" },
  "Matilda": { origin: "fornhögtyska Mahthildis", meaning: "'makt' och 'strid', alltså 'mäktig i strid'" },
  "Mats": { origin: "nordisk kortform av Mattias", meaning: "'Herrens gåva'" },
  "Matteus": { origin: "hebreiska Mattitjahu via grekiska Matthaios", meaning: "'Jahves gåva'" },
  "Mattias": { origin: "grekisk-latinsk form av hebreiska Mattitjahu", meaning: "'Jahves gåva'" },
  "Maud": { origin: "engelsk form av Matilda", meaning: "'mäktig i strid'" },
  "Maurits": { origin: "nederländsk form av latin Mauritius", meaning: "'moren' eller 'den mörkhyade'" },
  "Max": { origin: "kortform av Maximilian", meaning: "'den störste', av latin maximus" },
  "Maximilian": { origin: "latin Maximilianus, av Maximus", meaning: "'den störste'" },
  "Melker": { origin: "nordisk form av Melchior", meaning: "troligen hebreiska 'ljusets konung'", uncertain: true },
  "Mikael": { origin: "hebreiska Mîkhā'ēl", meaning: "'vem är som Gud?'", famous: ["Ärkeängeln Mikael", "Mikael Persbrandt, skådespelare"] },
  "Mikaela": { origin: "femininform av Mikael, hebreiska Mikha'el", meaning: "'vem är som Gud?'" },
  "Mimmi": { origin: "svensk smekform av Maria eller Wilhelmina", meaning: "beror på grundnamnet; Marias betydelse är omdiskuterad" },
  "Mirjam": { origin: "hebreiska Mirjam, den bibliska urformen till Maria", meaning: "'den upphöjda' eller 'den bittra' — omdiskuterad, möjligen egyptiskt ursprung" },
  "Moa": { origin: "svenskt namn av oklart ursprung", meaning: "möjligen till ett dialektalt ord för 'mor'", uncertain: true },
  "Mona": { origin: "kortform av Monika", meaning: "Monikas betydelse är omtvistad, ofta tolkad som 'den som förmanar'", uncertain: true },
  "Monika": { origin: "latin/grekiska", meaning: "'den ensamma' eller 'rådgiverska'", famous: ["Heliga Monika, Augustinus mor"] },
  "Morgan": { origin: "walesiska Morcant", meaning: "innehåller mor 'hav'; senare ledet är osäkert" },
  "Moritz": { origin: "tysk form av latin Mauritius", meaning: "'moren' eller 'den mörkhyade'" },
  "Moses": { origin: "hebreiska Mosche, troligen av egyptiska mes 'barn'", meaning: "i Bibeln tolkat som 'den som drogs upp ur vattnet'" },
  "Måns": { origin: "nordisk kortform av Magnus", meaning: "'den store', av latin magnus" },
  "Mårten": { origin: "nordisk form av latin Martinus", meaning: "'tillägnad krigsguden Mars'" },
  "Märit": { origin: "svensk form av Margareta", meaning: "'pärla'" },
  "Märta": { origin: "svensk form av Marta", meaning: "'härskarinna' (arameiska)", famous: ["Prinsessan Märtha av Sverige"] },
  "Nadja": { origin: "ryska smekform av Nadezjda", meaning: "'hopp'" },
  "Naemi": { origin: "hebreiska No'omi", meaning: "'den ljuvliga' eller 'min ljuvlighet'" },
  "Naima": { origin: "arabiska Na'ima; ibland uppfattat som variant av Naemi", meaning: "'den behagliga' eller 'den lyckliga'", uncertain: true },
  "Nanna": { origin: "fornnordiska Nanna, namn på Balders hustru", meaning: "troligen till ett ord för 'djärv'; betydelsen är omdiskuterad" },
  "Natalia": { origin: "latin Natalia, av natalis (dies) 'födelsedag'", meaning: "'den som föddes på juldagen'" },
  "Natalie": { origin: "fransk form av Natalia", meaning: "'den som föddes på juldagen'" },
  "Natanael": { origin: "hebreiska Netan'el", meaning: "'Gud har givit'" },
  "Niklas": { origin: "nordisk och tysk kortform av Nikolaus", meaning: "'folkets segrare'" },
  "Nikolaus": { origin: "grekiska Nikolaos", meaning: "'seger' och 'folk', alltså 'folkets segrare'" },
  "Nils": { origin: "nordisk kortform av Nikolaus", meaning: "'folkets segrare'" },
  "Ola": { origin: "nordisk kortform av Olof", meaning: "'förfädernas ättling', av fornnordiska Áleifr" },
  "Olaus": { origin: "latiniserad form av Olof", meaning: "'förfädernas ättling'" },
  "Olga": { origin: "ryska Olga, av fornnordiska Helga", meaning: "'den heliga' eller 'den vigda'" },
  "Oliver": { origin: "fornfranska Olivier", meaning: "vanligen till latin oliva 'olivträd', en fredssymbol; germanskt ursprung har också föreslagits" },
  "Olivia": { origin: "latin oliva", meaning: "'oliv' eller 'olivträd'" },
  "Olof": { origin: "fornnordiska Óláfr", meaning: "'ättling till sin förfader'", famous: ["Olof Palme (1927–1986), statsminister", "Olof Skötkonung, kung"] },
  "Orvar": { origin: "fornnordiska ǫrvar 'pilar', känt från sagohjälten Orvar-Odd", meaning: "'pilarnas man', alltså bågskytten" },
  "Oskar": { origin: "gaeliska Osgar, spritt genom Ossian-dikterna", meaning: "'hjortvän'; har också härletts ur fornnordiska Ásgeirr 'gudarnas spjut'" },
  "Ossian": { origin: "gaeliska Oisín, spritt genom Macphersons Ossian-dikter", meaning: "'liten hjort'" },
  "Osvald": { origin: "fornengelska Osweald", meaning: "'gud' och 'härskare', alltså 'gudomlig härskare'" },
  "Ottilia": { origin: "latiniserad form av fornhögtyska Odilia, femininform till Otto", meaning: "'den förmögna', av germanskt od 'rikedom, arvegods'" },
  "Otto": { origin: "fornhögtyska Otto, kortform av namn på Od-", meaning: "'rikedom' eller 'arvegods'" },
  "Ove": { origin: "danska Ove, av fornnordiska Áki", meaning: "osäker; möjligen smekform av namn på Ás- 'gud'", uncertain: true },
  "Patricia": { origin: "latin Patricia, femininform av Patricius", meaning: "'patricier', alltså 'av förnäm börd'" },
  "Patrik": { origin: "latin Patricius", meaning: "'av ädel börd'", famous: ["Patrik Sjöberg, höjdhoppare"] },
  "Paul": { origin: "latin Paulus", meaning: "'den lille'" },
  "Paula": { origin: "latin Paula, femininform av Paulus", meaning: "'den lilla'" },
  "Paulina": { origin: "latin Paulina, femininform av Paulinus", meaning: "'den lilla', utvidgning av Paulus" },
  "Per": { origin: "grekiska Petros", meaning: "'klippa, sten'", famous: ["Per Albin Hansson (1885–1946), statsminister", "Per Gessle, musiker"] },
  "Pernilla": { origin: "kortform av Petronella", meaning: "'liten klippa'", famous: ["Pernilla August, skådespelerska/regissör"] },
  "Peter": { origin: "grekiska Petros, översättning av arameiska Kefas", meaning: "'klippa' eller 'klippan'" },
  "Petra": { origin: "femininform av Peter, latin petra", meaning: "'klippa'" },
  "Petronella": { origin: "latin Petronius", meaning: "'liten klippa' — kvinnlig form av Petrus", famous: ["Heliga Petronella, romersk martyr"] },
  "Pia": { origin: "latin pia, femininform av pius", meaning: "'from' eller 'gudfruktig'" },
  "Pontus": { origin: "latin Pontus, av grekiska póntos", meaning: "'hav'; även landskapet Pontos i Mindre Asien" },
  "Pål": { origin: "nordisk form av latin Paulus", meaning: "'den lille'" },
  "Rafael": { origin: "hebreiska Refa'el", meaning: "'Gud har helat'" },
  "Ragna": { origin: "fornnordiska Ragna, kortform av namn på Ragn-", meaning: "'gudamakterna', av fornnordiska regin" },
  "Ragnar": { origin: "fornnordiska Ragnarr", meaning: "'gudamakter' och 'här', alltså 'gudarnas krigare'" },
  "Ragnhild": { origin: "fornnordiska Ragnhildr", meaning: "'gudarnas strid' — av regin 'gudamakter' och hildr 'strid'" },
  "Ragnvald": { origin: "fornnordiska Rǫgnvaldr", meaning: "'den som råder med gudarnas makt' — av regin 'gudamakter' och valdr 'härskare'" },
  "Rakel": { origin: "hebreiska Rachel", meaning: "'tacka', ett moderfår — biblisk, Jakobs hustru" },
  "Ralf": { origin: "engelska Ralph, av fornnordiska Ráðúlfr", meaning: "'rådets varg' — av ráð 'råd' och ulfr 'varg'" },
  "Raoul": { origin: "fransk form av germanska Radulf", meaning: "'rådets varg' — av rād 'råd' och wolf 'varg'" },
  "Rasmus": { origin: "kortform av grekiska Erasmus", meaning: "'den älskvärde, den efterlängtade' — av erasmios 'älskad, åtrådd'" },
  "Rebecka": { origin: "hebreiska Rivka", meaning: "'den fängslande'", famous: ["Rebecka i Bibeln, Isaks hustru"] },
  "Regina": { origin: "latin Regina", meaning: "'drottning'" },
  "Reidar": { origin: "fornnordiska Reiðarr", meaning: "'ryttarkrigare'", famous: ["Vanligt nordiskt mansnamn"] },
  "Reidun": { origin: "norska Reidun, bildat av fornnordiska namnled", meaning: "'bo, hem' eller 'ritt' förenat med unnr 'våg' eller 'älska'", uncertain: true },
  "Reine": { origin: "kortform av germanska namn på Ragin-, t.ex. Reinhold", meaning: "'råd, gudamakter'", uncertain: true },
  "Reinhold": { origin: "fornhögtyska Reginwald", meaning: "'den som råder med gudarnas makt' — av ragin 'gudamakter' och waldan 'råda'" },
  "Rigmor": { origin: "danska Rigmor, av lågtyska Richmod", meaning: "'mäktigt sinne' — av rīk 'mäktig' och mōd 'mod, sinne'" },
  "Rikard": { origin: "fornhögtyska Rīchard", meaning: "'stark härskare' — av rīk 'mäktig, härskare' och hard 'hård, stark'" },
  "Rita": { origin: "kortform av Margareta, via italienska Margherita", meaning: "'pärla'" },
  "Ritva": { origin: "finska ritva", meaning: "'smal björkkvist'" },
  "Robert": { origin: "fornhögtyska Hrodebert", meaning: "'strålande av ryktbarhet' — av hrod 'ära, rykte' och beraht 'ljus, strålande'" },
  "Robin": { origin: "engelska Robin, fornfransk smekform av Robert", meaning: "'strålande av ryktbarhet'" },
  "Roger": { origin: "fornhögtyska Hrodgar, motsvarar fornnordiska Hróðgeirr", meaning: "'ryktbart spjut' — av hrod 'ära, rykte' och gēr 'spjut'" },
  "Roland": { origin: "fornhögtyska Hrodland", meaning: "'ryktbar i landet' — av hrod 'ära, rykte' och land 'land'" },
  "Rolf": { origin: "fornnordiska Hrólfr, sammandragning av Hróðulfr", meaning: "'ryktbar varg' — av hróðr 'ära, rykte' och ulfr 'varg'" },
  "Ronald": { origin: "skotsk form av fornnordiska Rǫgnvaldr (Ragnvald)", meaning: "'den som råder med gudarnas makt' — av regin 'gudamakter' och valdr 'härskare'" },
  "Ronny": { origin: "engelsk smekform av Ronald", meaning: "'den som råder med gudarnas makt'" },
  "Rosa": { origin: "latin rosa", meaning: "'ros'" },
  "Rosita": { origin: "spansk diminutivform av Rosa", meaning: "'liten ros'" },
  "Roy": { origin: "skotska Roy, av gaeliska ruadh", meaning: "'röd, rödhårig'; ibland i stället härlett ur fornfranska roi 'kung'" },
  "Ruben": { origin: "hebreiska", meaning: "'se, en son!'", famous: ["Ruben, Jakobs äldste son i Bibeln", "Ruben Östlund, regissör"] },
  "Rudolf": { origin: "fornhögtyska Hrodulf", meaning: "'ryktbar varg' — av hrod 'ära, rykte' och wolf 'varg'" },
  "Rune": { origin: "fornnordiska rún", meaning: "'runa, hemlighet' — förtrolig kunskap" },
  "Rut": { origin: "hebreiska Rut", meaning: "'vänskap' eller 'den trogna'" },
  "Rutger": { origin: "lågtysk och nederländsk form av germanska Hrodger (samma namn som Roger)", meaning: "'ryktbart spjut' — av hrod 'ära, rykte' och gēr 'spjut'" },
  "Sabina": { origin: "latin Sabina", meaning: "'kvinna av sabinernas folk'" },
  "Salomon": { origin: "hebreiska Shelomo", meaning: "'den fridfulle' — av shalom 'frid'" },
  "Sam": { origin: "kortform av Samuel", meaning: "'Gud har hört'" },
  "Samuel": { origin: "hebreiska Shemuel", meaning: "'Gud har hört' eller 'hans namn är Gud'" },
  "Sandra": { origin: "kortform av italienska Alessandra (Alexandra)", meaning: "'hon som skyddar männen' — av grekiska alexein 'skydda' och aner 'man'" },
  "Sara": { origin: "hebreiska Sarah", meaning: "'furstinna'", famous: ["Sara Lidman (1923–2004), författare"] },
  "Sebastian": { origin: "grekiska, från Sebastos", meaning: "'den vördade'", famous: ["Heliga Sebastian, martyr", "Sebastian Stakset"] },
  "Selma": { origin: "keltiska", meaning: "'vacker utsikt'", famous: ["Selma Lagerlöf (1858–1940), författare, Nobelpristagare"] },
  "Set": { origin: "hebreiska Shet", meaning: "'den insatte, den utsedde' — biblisk, Adams tredje son" },
  "Seved": { origin: "fornsvenska Sighvidh, av fornnordiska Sigviðr", meaning: "'segerträ' — av sigr 'seger' och viðr 'trä, skog'" },
  "Severin": { origin: "latin Severinus, avlett av Severus", meaning: "'den stränge, den allvarlige'" },
  "Sibylla": { origin: "grekiska sibylla", meaning: "'spåkvinna, siarinna'" },
  "Sigbritt": { origin: "svensk nybildning av Sig- och Britt (av Birgitta)", meaning: "'seger' förenat med Britt 'den upphöjda, den starka'" },
  "Sigfrid": { origin: "fornhögtyska Sigfrid, motsvarar fornnordiska Sigfríðr", meaning: "'seger och fred' — av sig 'seger' och fridu 'fred, skydd'" },
  "Signe": { origin: "fornnordiska Signý", meaning: "'den nya segern' — av sigr 'seger' och nýr 'ny'" },
  "Signhild": { origin: "fornnordiska Signhildr", meaning: "'segerstrid' — av sigr 'seger' och hildr 'strid'" },
  "Sigrid": { origin: "fornnordiska Sigríðr", meaning: "'vacker seger'", famous: ["Sigrid Storråda, drottning"] },
  "Sigurd": { origin: "fornnordiska Sigurðr, äldre Sigvarðr", meaning: "'segerns väktare' — av sigr 'seger' och vǫrðr 'väktare, skydd'" },
  "Sigvard": { origin: "fornnordiska Sigvarðr, äldre form av samma namn som Sigurd", meaning: "'segerns väktare' — av sigr 'seger' och vǫrðr 'väktare, skydd'" },
  "Silvia": { origin: "latin Silvia, av silva 'skog'", meaning: "'hon från skogen'" },
  "Simon": { origin: "hebreiska Shimon", meaning: "'den som hör' eller 'den bönhörde'" },
  "Simone": { origin: "fransk och italiensk femininform av Simon", meaning: "'hon som hör'" },
  "Siri": { origin: "kortform av fornnordiska Sigríðr (Sigrid)", meaning: "'vacker seger' — av sigr 'seger' och fríðr 'vacker, älsklig'" },
  "Sissela": { origin: "svensk form av Cecilia", meaning: "'den blinda' — av latin caecus 'blind'" },
  "Siv": { origin: "fornnordiska Sif, Tors hustru", meaning: "'släktskap, svågerlag' — av sif 'förbund mellan släkter'" },
  "Sivert": { origin: "lågtysk form av Sigvard (Sigurd)", meaning: "'segerns väktare' — av sigr 'seger' och vǫrðr 'väktare'" },
  "Sixten": { origin: "fornnordiska Sigsteinn", meaning: "'segersten' — av sigr 'seger' och steinn 'sten'" },
  "Sofia": { origin: "grekiska sophia", meaning: "'visdom'", famous: ["Drottning Sofia (1836–1913)", "Prinsessan Sofia av Sverige"] },
  "Solbritt": { origin: "svensk nybildning av Sol och Britt (av Birgitta)", meaning: "'sol' förenat med Britt 'den upphöjda, den starka'" },
  "Solveig": { origin: "fornnordiska Sólveig", meaning: "'solens styrka' — av sól 'sol' och veig 'kraft, styrka'" },
  "Sonja": { origin: "rysk smekform av Sofia", meaning: "'vishet' — av grekiska sophia" },
  "Staffan": { origin: "svensk form av Stefan, av grekiska Stephanos", meaning: "'krans, krona' — den lagerkrönte" },
  "Stefan": { origin: "grekiska Stephanos", meaning: "'krona, lagerkrans'", famous: ["Stefan Löfven, statsminister", "Stefan Holm, höjdhoppare"] },
  "Stella": { origin: "latin stella", meaning: "'stjärna'" },
  "Stellan": { origin: "svenskt namn av omdiskuterat ursprung", meaning: "har knutits både till fornnordiska namnled och till latin stella 'stjärna'", uncertain: true },
  "Sten": { origin: "fornnordiska Steinn", meaning: "'sten' — hård och orubblig; vanlig efterled i namn som Torsten" },
  "Stig": { origin: "fornnordiska Stígr", meaning: "'vandraren' — av stíga 'stiga, vandra'" },
  "Stina": { origin: "kortform av Kristina", meaning: "'kristen'", famous: ["Stina Wirsén, illustratör", "Drottning Kristina"] },
  "Sture": { origin: "fornsvenskt tillnamn Sture", meaning: "'den motspänstige, den styvsinte'" },
  "Styrbjörn": { origin: "fornnordiska Styrbjǫrn", meaning: "'stridsbjörn' — av styrr 'strid, tumult' och bjǫrn 'björn'" },
  "Sune": { origin: "fornnordiska Suni, fornsvenska Sune", meaning: "'son'" },
  "Susanna": { origin: "hebreiska Shoshannah", meaning: "'lilja'" },
  "Svante": { origin: "kortform av Svantepolk, av västslaviska Svatopluk", meaning: "'helig skara' — av svet 'helig' och pluk 'här, skara'" },
  "Svea": { origin: "svenskt namn bildat till svear och Svea rike", meaning: "'kvinnan från svearnas land, Sverige'" },
  "Sven": { origin: "fornnordiska Sveinn", meaning: "'yngling, pojke'", famous: ["Sven Hedin (1865–1952), upptäcktsresande", "Sven-Bertil Taube, sångare"] },
  "Sverker": { origin: "fornsvenska Sværkir, av omdiskuterat ursprung", meaning: "har tolkats som 'den mörke', till svartr 'svart', men härledningen är osäker", uncertain: true },
  "Sylvester": { origin: "latin Silvester, av silva 'skog'", meaning: "'skogsmannen, den som hör skogen till'" },
  "Sylvia": { origin: "latin Silvia, variantstavning av samma namn", meaning: "'hon från skogen' — av silva 'skog'" },
  "Sören": { origin: "dansk form av latin Severinus", meaning: "'den stränge, den allvarlige'" },
  "Tage": { origin: "fornnordiska Taki, inlånat från danskan", meaning: "'den som tar emot' — till taka 'ta, gripa', ofta tolkat som 'borgensman'", uncertain: true },
  "Tanja": { origin: "rysk smekform av Tatjana (latin Tatiana)", meaning: "till det romerska släktnamnet Tatius; betydelsen är okänd", uncertain: true },
  "Tea": { origin: "kortform av Dorotea", meaning: "'guds gåva' — grekiska doron 'gåva' och theos 'gud'" },
  "Tekla": { origin: "grekiska Thekla, av Theokleia", meaning: "'guds ära' — theos 'gud' och kleos 'ära, rykte'" },
  "Teodor": { origin: "grekiska Theodoros", meaning: "'guds gåva' — theos 'gud' och doron 'gåva'" },
  "Teodora": { origin: "femininform av Teodor, grekiska Theodora", meaning: "'guds gåva'" },
  "Terese": { origin: "svensk form av Teresia", meaning: "ursprunget är omdiskuterat; kanske till den grekiska ön Thera eller till therizein 'skörda'", uncertain: true },
  "Teresia": { origin: "spanska Teresa, ytterst grekiska", meaning: "ursprunget är omdiskuterat; kanske till ön Thera eller therizein 'skörda'", uncertain: true },
  "Tiburtius": { origin: "latin Tiburtius", meaning: "'mannen från Tibur' — den romerska staden Tibur, nuvarande Tivoli" },
  "Tobias": { origin: "grekisk form av hebreiska Tobia", meaning: "'Herren är god' — tov 'god' och Jah, kortform av gudsnamnet" },
  "Toini": { origin: "finska Toini", meaning: "ursprunget är oklart; har knutits till finska toinen 'den andra'", uncertain: true },
  "Tomas": { origin: "arameiska", meaning: "'tvilling'", famous: ["Aposteln Tomas tvivlaren", "Tomas Tranströmer (1931–2015), Nobelpristagare"] },
  "Tony": { origin: "engelsk kortform av Anthony, av latin Antonius", meaning: "betydelsen är okänd — Antonius var ett romerskt släktnamn av troligen etruskiskt ursprung" },
  "Tor": { origin: "fornnordiska Þórr", meaning: "'åska, dunder' — åskgudens namn, till germanska thunraz 'åska'" },
  "Tora": { origin: "fornnordiska Þóra, femininform av Tor", meaning: "'tillägnad guden Tor'" },
  "Torbjörn": { origin: "fornnordiska Þorbjǫrn", meaning: "'Tors björn' — guden Tor och bjǫrn 'björn'" },
  "Torborg": { origin: "fornnordiska Þorbjǫrg", meaning: "'Tors skydd' — guden Tor och bjǫrg 'hjälp, värn'" },
  "Tord": { origin: "fornnordiska Þórðr, sammandragning av Þorfreðr", meaning: "'Tors fred' — guden Tor och friðr 'fred, skydd'" },
  "Tore": { origin: "fornnordiska Þórir", meaning: "bildat till guden Tor; andra leden är osäker, möjligen vér 'krigare'", uncertain: true },
  "Torgny": { origin: "fornnordiska Þorgnýr", meaning: "'Tors dån' — guden Tor och gnýr 'larm, dån', alltså åskdånet" },
  "Torkel": { origin: "fornnordiska Þorketill", meaning: "'Tors offerkittel' — guden Tor och ketill 'kittel'" },
  "Torleif": { origin: "fornnordiska Þorleifr", meaning: "'Tors arvinge' — guden Tor och leifr 'kvarlämnad, ättling'" },
  "Torsten": { origin: "fornnordiska Þorsteinn", meaning: "'Tors sten' — guden Tor och steinn 'sten'" },
  "Torun": { origin: "fornnordiska Þórunnr", meaning: "'Tors våg' — guden Tor och unnr 'våg', eller till unna 'älska'" },
  "Torvald": { origin: "fornnordiska Þorvaldr", meaning: "'den som råder genom Tor' — guden Tor och valdr 'härskare'" },
  "Tove": { origin: "fornnordiska Tófa, kortform av namn på Þór-", meaning: "'helgad åt Tor'" },
  "Tryggve": { origin: "fornnordiska Tryggvi", meaning: "'trygg, trofast, pålitlig' — till tryggr" },
  "Ture": { origin: "fornsvenska Thure, kortform av namn på Þór-", meaning: "'Tor' — till åskguden Þórr" },
  "Turid": { origin: "fornnordiska Þuríðr", meaning: "'Tors sköna' — guden Tor och fríðr 'vacker, älskad'" },
  "Tyko": { origin: "latiniserad form av grekiska Tychon", meaning: "'den som träffar rätt' eller 'den lyckosamme' — till tyche 'lycka'" },
  "Tyra": { origin: "fornnordiska Þýri", meaning: "bildat till guden Tor; andra leden är omdiskuterad", uncertain: true },
  "Ulf": { origin: "fornnordiska Úlfr", meaning: "'varg'" },
  "Ulla": { origin: "kortform av Ulrika", meaning: "'den som råder över arvegodset'" },
  "Ulrik": { origin: "fornhögtyska Uodalrih", meaning: "'den som råder över arvegodset' — uodal 'fädernearv' och rihhi 'mäktig'" },
  "Ulrika": { origin: "femininform av Ulrik", meaning: "'den som råder över arvegodset'" },
  "Uno": { origin: "latin unus", meaning: "'en' — tolkat som 'den ende' eller 'den förstfödde'" },
  "Urban": { origin: "latin urbanus", meaning: "'från staden, belevad'", famous: ["Flera påvar vid namn Urban", "Urbandagen 25/5 var en gammal väderprofet"] },
  "Ursula": { origin: "latin Ursula, diminutiv av ursa", meaning: "'liten björnhona'" },
  "Valborg": { origin: "fornhögtyska Walburga", meaning: "'mäktigt skydd'", famous: ["Helgon Walburga", "Valborgsmässoafton firas till hennes ära"] },
  "Valdemar": { origin: "nordisk form av slaviska Vladimir", meaning: "'den store härskaren' — volod 'härska' och mer 'stor, berömd'" },
  "Valentin": { origin: "latin Valentinus, till valens", meaning: "'den starke, den friske' — till valere 'vara stark'" },
  "Valfrid": { origin: "fornhögtyska Waldfrid", meaning: "'den som råder i fred' — walt 'makt, välde' och fridu 'fred, skydd'" },
  "Valter": { origin: "fornhögtyska Walthari", meaning: "'härskare över hären' — waltan 'härska' och heri 'krigshär'" },
  "Vanja": { origin: "rysk smekform av Ivan, som motsvarar Johannes", meaning: "'Herren är nådig' — hebreiska Jochanan" },
  "Vega": { origin: "stjärnnamnet Vega, ytterst arabiska al-waqi", meaning: "'den störtande (örnen)' — huvudstjärnan i Lyran; spritt i Sverige genom Vegaexpeditionen 1878–1880" },
  "Veine": { origin: "svensk form av finska Väinö", meaning: "till Väinämöinen i Kalevala; betydelsen är oklar", uncertain: true },
  "Vendela": { origin: "femininform av Vendel, till folknamnet vender", meaning: "'venderskan' — kvinna av vendernas folk" },
  "Vera": { origin: "ryska / latin", meaning: "'tro' (ry.) eller 'sann' (lat.)", famous: ["Vera Nilsson (1888–1979), konstnär"] },
  "Verner": { origin: "fornhögtyska Werinher", meaning: "'krigare ur varinernas folk' — folknamnet warin och heri 'krigshär'" },
  "Veronika": { origin: "grekiska/latin", meaning: "'den sanna bilden' (vera icon)", famous: ["Heliga Veronika som torkade Jesu ansikte"] },
  "Vibeke": { origin: "dansk form av lågtyska Wibke, kortform av Wigburg", meaning: "'stridens skydd' — wig 'strid' och burg 'värn, borg'" },
  "Vidar": { origin: "fornnordiska Víðarr, namn på Odens son", meaning: "'den vittfarne krigaren' — víðr 'vid, vidsträckt' och en andra led som tolkas som 'krigare'", uncertain: true },
  "Viktoria": { origin: "latin victoria", meaning: "'seger' — även den romerska segergudinnans namn" },
  "Vilhelm": { origin: "fornhögtyska Willahelm", meaning: "'den beslutsamme beskyddaren' — willo 'vilja' och helm 'hjälm, skydd'" },
  "Vilhelmina": { origin: "fornhögtyska Wilhelm", meaning: "'beslutsam beskyddare'", famous: ["Drottning Vilhelmina av Nederländerna", "Staden Vilhelmina i Lappland"] },
  "Vilma": { origin: "kortform av Vilhelmina", meaning: "'beslutsam beskyddare'" },
  "Vincent": { origin: "latin Vincentius, till vincere", meaning: "'den segrande'" },
  "Viola": { origin: "latin viola", meaning: "'viol' — blomnamnet" },
  "Virginia": { origin: "latin, av det romerska släktnamnet Verginius", meaning: "'jungfrulig' — tidigt omtolkat efter virgo 'jungfru'" },
  "Viveka": { origin: "lågtyska Wibeke, kortform av Wigburg", meaning: "'stridens skydd' — wig 'strid' och burg 'värn, borg'" },
  "Vivianne": { origin: "fransk form av latin Viviana", meaning: "'den levande, den livfulla' — till vivus 'levande'" },
  "Volmar": { origin: "tysk variant av Valdemar", meaning: "'den ryktbare härskaren'; namnet har även knutits till fornhögtyska Folkmar 'folkets berömde'", uncertain: true },
  "William": { origin: "engelsk form av Vilhelm", meaning: "'den beslutsamme beskyddaren' — willo 'vilja' och helm 'hjälm, skydd'" },
  "Ylva": { origin: "fornnordiska Ylfa, femininform av Ulf", meaning: "'varginna'" },
  "Yngve": { origin: "fornnordiska Yngvi, binamn på guden Frej", meaning: "gudanamn knutet till germanska Ingwaz och Ynglingaätten; betydelsen är omdiskuterad", uncertain: true },
  "Yrsa": { origin: "fornnordiska Yrsa", meaning: "ursprunget är oklart; har härletts både till latin ursa 'björnhona' och till fornnordiska yrr 'vild'", uncertain: true },
  "Yvonne": { origin: "franska, av germanskt Yvo", meaning: "'idegran' (bågträ)", famous: ["Yvonne Ryding, Miss Universum 1984"] },
  "Åke": { origin: "fornnordiska Áki", meaning: "'förfader' eller 'liten fader'", famous: ["Åke Grönberg, skådespelare"] },
  "Åsa": { origin: "fornnordiska Ása, kortform av namn på Ás-", meaning: "'gudinna' — till áss 'asagud'" },
  "Åslög": { origin: "fornnordiska Áslaug", meaning: "'vigd åt gudarna' — áss 'gud' och andra leden -laug 'trolovad, vigd'" },
  "Örjan": { origin: "svensk form av Georgius, via lågtyska Jurgen", meaning: "'jordbrukare' — grekiska ge 'jord' och ergon 'arbete'" },
  "Östen": { origin: "fornnordiska Eysteinn", meaning: "'lyckans sten' — ey 'lycka, alltid' och steinn 'sten'" },
};

export function nameInfo(name) {
  return NAME_INFO[name] || null;
}
